### PR TITLE
Increase distributed buffer for riak

### PR DESCRIPTION
**Pull request by johnSchnake**
For performance, we should increase +zdbbl from the default 32k.
http://riak.com.cn/riakcs/1.4.1/cookbooks/configuration/Configuring-Riak/
recommends 96k and sometimes 128k.

At the cost of memory this will decrease latency and potentially
increase reliability.

Related: #ENGT-8478
@shobhit85 @bwerthmann

### CODE REVIEW

**Comment by shobhit85** [comment]
LGTM

**Comment by johnSchnake** [comment]
Tests running currently; on another set of logs I have we started hitting the high water mark for memory ~20 min after starting riak.  The logs have about an hour of data and still no high water marks. I'm hoping this is the only fix we need.

I suggest merging this if there are no obvious problems (a failed test wont be a result of this, so as long as the run is generally OK) that we merge this and monitor hangs for the next day or two. If there are still problems then we can still introduce the retry logic.  Thoughts? 

@lilirui I know you thought the retry logic was good to have, but if this resolves the issue do you think it is still necessary?

Wouldn't really be _bad_ to introduce the retry logic anyways but its kind of poor form to retry things unnecessarily.

**Comment by shobhit85** [comment]
SGTM @johnSchnake Agree should try this fix first for few days.

**Comment by lilirui** [comment]
@johnSchnake If this can fix the riak issue fundamentally then I'm Ok to not merge the retry.

**Comment by zquestz** [comment]
Agreed. Great find.  LGTM

**Pull request merged**
